apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJTWEpoVUc5c2RXSmxjenBuYUhCZlpUUlNlVXRSU1ZCaVUwY3hSa3g0U1Rjd09IUjBiVE5XTW1OeVJHaHlNMGRDZUdkbiIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
